before:
  hooks:
    - go mod tidy
builds:

- id: "kubectl-fzf-server"
  main: cmd/kubectl-fzf-server/main.go
  binary: kubectl-fzf-server
  env:
    - CGO_ENABLED=0
  ldflags:
  - -X main.GitCommit={{.Commit}} -X main.GitBranch={{.Tag}} -X main.BuildDate={{.Date}} -X main.Version={{.Version}}
  goos:
    - darwin
    - linux
  goarch:
    - amd64

- id: "kubectl-fzf-completion"
  main: cmd/kubectl-fzf-completion/main.go
  binary: kubectl-fzf-completion
  env:
    - CGO_ENABLED=0
  ldflags:
  - -X main.GitCommit={{.Commit}} -X main.GitBranch={{.Tag}} -X main.BuildDate={{.Date}} -X main.Version={{.Version}}
  goos:
    - darwin
    - linux
  goarch:
    - amd64

archives:
- id: kubectl-fzf
  files:
    - README.md
    - LICENSE
    - shell/kubectl_fzf.sh
    - shell/kubectl_fzf_completion.zsh
    - shell/kubectl_fzf_completion.bash
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - image_templates:
    - "bonnefoa/kubectl-fzf:{{ .Tag }}"
    - "bonnefoa/kubectl-fzf:v{{ .Major }}"
    - "bonnefoa/kubectl-fzf:v{{ .Major }}.{{ .Minor }}"
    - "bonnefoa/kubectl-fzf:latest"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: bonnefoa
    name: kubectl-fzf
  draft: true
  prerelease: auto
  name_template: "v{{.Version}}"
  disable: false

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
