before:
  hooks:
    - go mod tidy
builds:
- id: "kfzf_server"
  main: cmd/kfzf_server/main.go
  binary: kfzf_server
  env:
    - CGO_ENABLED=0
  ldflags:
  - -X main.GitCommit={{.Commit}} -X main.GitBranch={{.Tag}} -X main.BuildDate={{.Date}} -X main.Version={{.Version}}

  goos:
    - darwin
    - linux

  goarch:
    - amd64
archives:
- id: kfzf_server
  files:
    - README.md
    - LICENSE
    - kubectl_fzf.bash
    - kubectl_fzf.example.yaml
    - kubectl_fzf.plugin.zsh
    - kubectl_fzf.sh
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: bonnefoa
    name: kubectl-fzf
  draft: true
  prerelease: auto
  name_template: "v{{.Version}}"
  disable: false

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
