apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    chart: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
data:
  .kubectl_fzf.yaml: |
    ignore-node-roles:
      - compute
    exclude-namespaces:
      - consul-agent
      - go-audit
      - local-volume-provisioner
      - localusers
      - kube2iam
      - devenv-.*
