apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    chart: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  template:
    metadata:
      name: {{ $.Chart.Name }}
      labels:
        app: {{ $.Chart.Name }}
        chart: {{ $.Chart.Name }}
        chart_version: {{ $.Chart.Version }}
      annotations:
        checksum/configs: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ $.Chart.Name }}
      {{- if $.Values.toleration }}
      tolerations:
      - key: node
        operator: Equal
        value: {{ $.Values.toleration }}
        effect: NoSchedule
      {{- end }}
      containers:
      - name: cache-builder
        image: {{ $.Values.image.kubectl_fzf_server.name }}:{{ $.Values.image.kubectl_fzf_server.tag }}
        imagePullPolicy: {{ $.Values.docker.pullPolicy }}
        volumeMounts:
        - name: config
          mountPath: /etc/kubectl_fzf
        - name: cache
          mountPath: /tmp/kubectl_fzf_cache
        resources:
          requests:
            memory: {{ $.Values.resources.kubectl_fzf_server.memory }}
            cpu: {{ $.Values.resources.kubectl_fzf_server.cpu }}
          limits:
            memory: {{ $.Values.resources.kubectl_fzf_server.memory }}
            cpu: {{ $.Values.resources.kubectl_fzf_server.cpu }}
        ports:
          - containerPort: {{ $.Values.port }}
        args:
          - --cluster-name=$(K8S_CLUSTER_INFRA_DOMAIN)
          - --log-level=info
          - --listen-address=localhost:{{ $.Values.port }}
          - --http-debug

      volumes:
      - name: config
        configMap:
          name: {{ $.Chart.Name }}-config
      - name: cache
        emptyDir: {}
