apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Chart.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    chart: {{ $.Chart.Name }}
    chart_version: {{ $.Chart.Version }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - pods
  - secrets
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - list
  - watch

- apiGroups:
  - extensions
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - list
  - watch

- apiGroups:
  - extensions
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch

- apiGroups:
  - extensions
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - watch

- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Chart.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    chart: {{ $.Chart.Name }}
    version: {{ $.Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ $.Chart.Name }}
  namespace: {{ .Release.Namespace }}
